### ISSUE TITLE
Youtube downloading problems: they seem to have blacklisted our IP

### ISSUE THREAD

**Issue by kathiedart** [kathiedart/projectchaplin#161]
While setting up projectchaplin.com up again, Youtube has blocked our IP range.

This doesn't sound like good news, but with enough nodes I suppose we can delegate?
Otherwise, captchas etc would have to be put in place... which is just nasty, etc.

I don't think stopping supporting Youtube is sensible, but as they have huge import restrictions there should be another way, such as through a 3rd party service perhaps?

Any ideas?

Related: https://github.com/rg3/youtube-dl/issues/5138

**Comment by dandart** [comment]
YouTube seems to want to have a say in how other people distribute their videos:
https://www.youtube.com/static?gl=US&template=terms
Their terms of use sound like they're against licences of CC videos uploaded to youtube... but it sounds like because they explicitly only use CC-BY as a licence, they can relicence to not be distributable (as it's not SA).

Disappointing, but I shall have a chat with the YouTube staff about this peculiarity.

**Comment by dandart** [comment]
Well I've tweeted them, let's hope they get back to me soon enough.

**Comment by kathiedart** [comment]
They are absolutely silent, that's not good at all.

**Comment by kathiedart** [comment]
Aha, looks by the above that we need to force ipv4 as LOTS of ipv6 has been blocked. Eurgh.

**Comment by kathiedart** [comment]
That looks to now behave a lot better! Huzzah!

**Comment by adamwoo2444** [comment]
hey can you help me out @danwdart .

**Comment by adamwoo2444** [comment]
I am facing a similar issue. Please
